apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: registry.gitlab.com/onkarpathak/spring-starter-gke
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: test-app-registry
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels:
    app: test-app
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: test-app
  type: LoadBalancer
